---

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint everything
    steps:
      - uses: actions/checkout@v2
      - uses: oarmstrong/olint@v1
